[sc-98256] Handling offset pagination on APIs returning an array
dataiku/dss-plugin-api-connect pull request #24
Opened 2022-08-30 07:36 UTC by alexbourret

2022-09-19 16:08 UTC, liamlynch-data requested changes
Discovered while testing and discussing this, that the mock API was handling the empty/final request unrealistically, and the code needs to handle one of the following realistic cases for the last response:
- empty list
- 404

While at the moment it will either error out or add an empty row at the end, so this needs some work.

2022-09-21 06:57 UTC, alexbourret commented on python-lib/pagination.py
> +                    return True
👍 done in [f80ccdc](https://github.com/dataiku/dss-plugin-api-connect/pull/24/commits/f80ccdc20ab01ead027e576b4a2686966fc36d23)

2022-09-21 07:03 UTC, alexbourret commented
After looking back at the initial specs for this fix, it appears that the targeted server outputs an empty list when the skip/page number goes beyond the last existing record. Rapid survey shows the same thing, no case of 404 was found.
For now we'll fix the integration test's mock server to reflect this behavior and implement 404 handling at later stage if such an API is ever found.

2022-09-21 07:05 UTC, liamlynch-data approved these changes

2022-09-21 09:51 UTC, merged